const PATH_BASE = 'http://localhost:8080';
const PATH_LOGIN = '/login';
const PATH_USER_DETAILS='/userDetails';
const PATH_REQUESTS ='/requests';
const PATH_INCIDENTS='/incident';
const PATH_INCIDENTS_GET='/getAll';
const PATH_CREATE_INCIDENT='/create';
const PATH_UN_INCIDENTS_GET='/unassigned';
const PATH_ONE_INCIDENT='/getIncidentDetail';
const PATH_ESCALATION_ADMIN='/escalation';
const PATH_ASSIGN_ADMIN='/assignIncident';
const PATH_RESOLVE_INCIDENT='/resolve';
const PATH_ASSIGN_RESOLVER='/assignResolver';
const PATH_ESCALATION_RESOLVER='/resolveEscalation';
const PATH_CLOSE_INCIDENT='/closeIncident';
const PATH_INCIDENT_MESSAGE='/incidentMessages';
const PATH_SEND_INCIDENT_MESSAGE='/send';
const PATH_GET_INCIDENT_MESSAGE='/getAll';

export {

	PATH_BASE,
  	PATH_LOGIN,
	PATH_USER_DETAILS,
	PATH_REQUESTS,
	PATH_INCIDENTS,
	PATH_CREATE_INCIDENT,
	PATH_INCIDENTS_GET,
	PATH_UN_INCIDENTS_GET,
	PATH_ONE_INCIDENT,
	PATH_ESCALATION_ADMIN,
	PATH_ASSIGN_ADMIN,
	PATH_RESOLVE_INCIDENT,
	PATH_ASSIGN_RESOLVER,
	PATH_ESCALATION_RESOLVER,
	PATH_CLOSE_INCIDENT,
	PATH_INCIDENT_MESSAGE,
	PATH_SEND_INCIDENT_MESSAGE,
	PATH_GET_INCIDENT_MESSAGE
}
